[pytest]
filterwarnings =
    ignore::DeprecationWarning:gherkin.*
python_files =
    key/steps/test_key_pc_*.py
pythonpath = .
addopts = -v -s --alluredir=allure_results --clean-alluredir --headed
bdd_features_base_dir = features
asyncio_default_fixture_loop_scope:session
markers =
    key_pc
    P0
    P1
    P2
    P3
